spring:
  profiles:
    group:
#      develop: dev, swagger, redis, jwt
#      production: prod, swagger, redis, jwt
#    default: production

        develop:
          - dev
          - swagger
          - redis
          - jwt
          - mail
        production:
          - prod
          - swagger
          - redis
          - jwt
          - mail
        default: production