server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${app.db.host}:${app.db.port}/${app.db.name}
    username: ${app.db.user}
    password: ${app.db.password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
  banner:
    location: banner/banner.txt
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

logging:
  level:
    com.pavbatol: DEBUG
    org.springframework.web: DEBUG

app:
  db:
    host: localhost
    port: 5432
    name: t-core
    user: postgres
    password: 12345
  auth-service:
    url: http://localhost:8078
    path:
      private-user: /private/user
      admin-user: /admin/user
  data:
    file-path:
      countries: src/main/resources/file/country-codes_short.csv
      high-schools: src/main/resources/file/high_schools_edu-ru.xlsx
      cities: src/main/resources/file/openstreetmap/export_city_russia.geojson,
        src/main/resources/file/openstreetmap/export_town_russia.geojson, 
        src/main/resources/file/openstreetmap/export_city_usa_and_part_europe.geojson, 
        src/main/resources/file/openstreetmap/export_city_all_without_usa.geojson


