server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
#    url: jdbc:h2:file:./db/t-core
    username: test
    password: test
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data-dev.sql
  banner:
    location: banner/banner-dev.txt
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

logging:
  level:
    com.pavbatol: DEBUG
    org.springframework.web: DEBUG

app:
  db:
    host: localhost
    port: 5432
    name: t-core
    user: postgres
    password: 12345
  auth-service:
    url: http://localhost:8078
    path:
      private-user: /private/user
      admin-user: /admin/user
  data:
    file-path:
      countries: src/main/resources/file/country-codes_short.csv
      high-schools: src/main/resources/file/high_schools_edu-ru.xlsx
