spring:
  profiles:
    group:
        develop:
          - dev
          - swagger
          - mail
          - jwt
        production:
          - prod
          - swagger
          - mail
          - jwt
        default: production