spring:
  profiles:
    group:
        develop:
          - dev
          - swagger
          - mail
        production:
          - prod
          - swagger
          - mail
        default: production